gresrun/jesque

src/main/java/net/greghaines/jesque/meta/dao/impl/KeysDAORedisImpl.java
Exception was thrown running a custom jesque-web with a DB from redislabs.com (Redis version 2.8.12)
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:658)
at net.greghaines.jesque.meta.dao.impl.KeysDAORedisImpl$2.doWork(KeysDAORedisImpl.java:122)
at net.greghaines.jesque.meta.dao.impl.KeysDAORedisImpl$2.doWork(KeysDAORedisImpl.java:112)
at net.greghaines.jesque.utils.PoolUtils.doWorkInPool(PoolUtils.java:58)
at net.greghaines.jesque.utils.PoolUtils.doWorkInPoolNicely(PoolUtils.java:82)
at net.greghaines.jesque.meta.dao.impl.KeysDAORedisImpl.getRedisInfo(KeysDAORedisImpl.java:112)
at net.greghaines.jesque.web.controller.JesqueController.stats(JesqueController.java:230)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native …
```
=> fixed StringIndexOutOfBoundsException

src/main/java/net/greghaines/jesque/Config.java, src/main/java/net/greghaines/jesque/ConfigBuilder.java, src/main/java/net/greghaines/jesque/utils/JesqueUtils.java, src/test/java/net/greghaines/jesque/TestConfigBuilder.java, src/test/java/net/greghaines/jesque/utils/TestJesqueUtils.java
In the current implementation a `namespace` is required. By default it's set to `resque` but it cannot be set to an empty string or nil.
Sidekiq by default uses no namespace so to get this to work with Sidekiq you have to set a `namespace` so that the namespaces from jesque and Sidekiq match up. See also http://stackoverflow.com/questions/21974356/how-to-enqueue-a-job-in-sidekiq-with-java-or-scala
It would be nice if you could specify nil or empty namespace in jesque so it will would with Resque and Sidekiq out of the box.
=> Empty namespace

src/main/java/net/greghaines/jesque/client/ClientImpl.java
I'm getting the following error when trying to shutdown the jesqueClient:
```
Exception in thread "Thread-7" redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection timed out
at redis.clients.jedis.Connection.flush(Connection.java:276)
at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:179)
at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:136)
Caused by: java.net.SocketException: Connection timed out
at java.net.SocketOutputStream.socketWrite0(Native Method)
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31)
at …
```
=> Ensure Jedis Connection before tying to quit jedis

pom.xml
AFAIK Jesque heavily relied on BinaryJedis.quit().
Recently we found an issue on BinaryJedis.quit(), and it was fixed. 
Please refer https://github.com/xetorthio/jedis/commit/aa9a5e25996df0c425fcb07ba94f33f9457e832d
It's published only 2.7.0, so I recommend jesque to upgrade Jedis to 2.7.0.
Thanks!
=> Apply Jedis 2.7.0

src/main/java/net/greghaines/jesque/client/AbstractClient.java, src/main/java/net/greghaines/jesque/client/Client.java, src/main/java/net/greghaines/jesque/client/ClientImpl.java, src/main/java/net/greghaines/jesque/client/ClientPoolImpl.java, src/main/java/net/greghaines/jesque/utils/JedisUtils.java, src/main/java/net/greghaines/jesque/utils/JesqueUtils.java, src/main/java/net/greghaines/jesque/utils/ResqueConstants.java, src/main/java/net/greghaines/jesque/worker/WorkerImpl.java, src/test/java/net/greghaines/jesque/RecurringQueueTest.java, src/test/java/net/greghaines/jesque/RemoveDelayedQueueTest.java
* a recurring job has a schedule in zset with the next timestamp as the
score
* the frequency of the job is stored in a hash
* on pop the frequency and the score are summed up to form the new score
and added back to the zset
* a delete recurring removes it from the zset and hash
* add delete and pop operations run on a redis transaction
related issue #77
=> add recurring feature that allows running a job every N seconds

pom.xml, src/main/java/net/greghaines/jesque/Config.java, src/main/java/net/greghaines/jesque/ConfigBuilder.java, src/main/java/net/greghaines/jesque/utils/PoolUtils.java, src/test/java/net/greghaines/jesque/TestConfigBuilder.java, src/test/java/net/greghaines/jesque/utils/TestPoolUtils.java
Currently the test for the sentinel is set to ignore.  You can manually start up a sentinel and a master redis server and uncomment the @ignore to test.
=> Support for Redis Sentinel

src/main/java/net/greghaines/jesque/worker/Worker.java, src/main/java/net/greghaines/jesque/worker/WorkerImpl.java, src/main/java/net/greghaines/jesque/worker/WorkerPool.java, src/main/java/net/greghaines/jesque/worker/WorkerPoolImpl.java, src/main/resources/workerScripts/fromMultiplePriorityQueues.lua, src/test/java/net/greghaines/jesque/worker/TestWorkerImpl.java, src/test/java/net/greghaines/jesque/worker/TestWorkerPool.java
This PR adds ability to provide a list of queues 
`[first_priority, second_priority, third_priority, ...]`
and receive the first message available.
This is done via a single _Redis_ command that iterates **_server-side**_ on the provided list of queues.
Suggestions how to improve this PR are welcome :tada:
=> MultiplePriorityQueues: Add ability to POP first message from a list of queues

src/main/java/net/greghaines/jesque/worker/DefaultFailQueueStrategy.java, src/main/java/net/greghaines/jesque/worker/FailQueueStrategy.java, src/main/java/net/greghaines/jesque/worker/WorkerImpl.java, src/main/java/net/greghaines/jesque/worker/WorkerPoolImpl.java
By default there is no upper limit for the amount of items to keep in a failed queue.
If there are many failing jobs with huge stacktraces, the redis instance may go OOM.
We're currently doing this in our own `execute` implementation, would be nice to have this upstream so others could use this as well.
=> allow to set a max number of failed items to keep via FailQueueStrategy

src/main/java/net/greghaines/jesque/worker/WorkerPoolImpl.java
The `nextQueueStrategy` feature was added in #107, but only for `WorkerImpl`.
This patch adds the feature also to the `WorkerPoolImpl`.
=> add nextQueueStrategy feature to WorkerPoolImpl

.gitignore, pom.xml, src/main/java/net/greghaines/jesque/json/ObjectMapperFactory.java, src/main/java/net/greghaines/jesque/utils/CompositeDateFormat.java
I think my pull request addresses this issue: #137
I suspect the problem will become more common. DropWizard (our framework) upgraded to Jackson 2.9.x at version 1.2 and they are at 1.3.1 now.
The upgrade broke how the date serializer worked. I verified that all unit tests pass. I also verified through my app that normal queuing, delayed queuing, and scheduled recurring queuing all work. Workers also pick up and process jobs as expected.
Thank you for putting this project out, it's very useful.
=> upgrade to jackson 2.9.5

src/main/java/net/greghaines/jesque/worker/WorkerImpl.java
fixes https://github.com/gresrun/jesque/issues/100
=> Reload redis scripts on reconnect

src/main/java/net/greghaines/jesque/worker/WorkerImpl.java, src/main/java/net/greghaines/jesque/worker/WorkerPoolImpl.java
we missed pushing the JobFailure in the case when there is a fail queue item limit and the current number of failed items is 0
the fix is to call rpush in this case as well
=> fix case where we missed pushing a JobFailure

src/main/java/net/greghaines/jesque/Job.java, src/main/java/net/greghaines/jesque/meta/dao/impl/QueueInfoDAORedisImpl.java, src/test/java/net/greghaines/jesque/meta/dao/impl/TestQueueInfoDAORedisImpl.java
This patch adds a `runAt` property to the `Job` class. 
The property is set by `QueueInfoDAORedisImpl#getQueueInfo`, but only when the queue is a delayed one.
The property is exposed via `QueueInfo.getJobs()*.runAt`.
=> add runAt property to job

src/main/java/net/greghaines/jesque/meta/QueueInfo.java, src/main/java/net/greghaines/jesque/meta/dao/impl/QueueInfoDAORedisImpl.java, src/test/java/net/greghaines/jesque/meta/dao/impl/TestQueueInfoDAORedisImpl.java
For delayed queues, the size property may be misleading,
as it shows all jobs that are enqueued in that queue.
This patch adds a `pending` property to the QueueInfo class
which shows the number of jobs in a delayed queue that are
eligible for execution by a worker.
=> add pending property to QueueInfo

src/main/java/net/greghaines/jesque/worker/WorkerImpl.java, src/main/java/net/greghaines/jesque/worker/WorkerPoolImpl.java, src/main/resources/workerScripts/fromMultiplePriorityQueues.lua
Providing namespace in the lua script that supports priority queues
=> Supporting non default namespace when NextQueueStrategy is RESET_TO_HIGHEST_PRIORITY

pom.xml
Hi,
This PR updates jackson to version 2.9.8, since 2.9.6 has known vulnerabilities.
Snyk: https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72449
CVEs: CVE-2018-14718, CVE-2018-14719, CVE-2018-14720, CVE-2018-14721, CVE-2018-14722, CVE-2018-14723
CWEs: [CWE-502](https://cwe.mitre.org/data/definitions/502.html)
=> upgrade to jackson 2.9.8

README.md, src/main/java/net/greghaines/jesque/client/AbstractClient.java, src/main/java/net/greghaines/jesque/client/Client.java, src/main/java/net/greghaines/jesque/client/ClientImpl.java, src/main/java/net/greghaines/jesque/client/ClientPoolImpl.java, src/test/java/net/greghaines/jesque/IntegrationTest.java, src/test/java/net/greghaines/jesque/Issue56Test.java, src/test/java/net/greghaines/jesque/TestUtils.java
This change allows enqueueing a list of jobs with higher performance than one-by-one invoking the existing `client.enqueue()` method. It therefore uses Redis Pipelining: https://redis.io/topics/pipelining.
I decided against supporting splitting the list of jobs into chunks of e.g. 10,000 jobs, which is recommended by Redis ('Important Note' at https://redis.io/topics/pipelining#redis-pipelining). I mentioned this in the JavaDoc and left it to the client of this method to keep the library simple. Some clients might want to ignore this and I wanted to leave it up to the user.
This change also includes a bit of refactoring of the `validate` methods to be able to validate the queue name parameter independently of a job parameter.
Closes https://github.com/gresrun/jesque/issues/123
=> allow batch enqueueing of jobs using Redis Pipelining

src/main/java/net/greghaines/jesque/worker/DefaultPoolExceptionHandler.java
we just discovered that the reconnect implemented in #149 does not work properly: the exception message has a [\r\n at the end](https://github.com/redis/redis/blob/unstable/src/server.c#L2240). so calling `equals` always returns false and hence the workers will terminate.
the fix is to call `startsWith` instead.
=> fix detection of redis loading the dataset

src/main/java/net/greghaines/jesque/meta/dao/FailureDAO.java, src/main/java/net/greghaines/jesque/meta/dao/impl/FailureDAORedisImpl.java, src/test/java/net/greghaines/jesque/meta/dao/impl/TestFailureDAORedisImpl.java
the failure dao currently only provides a counter for the amount of jobs
in the failed queue. this patch adds the possibility to retrieve the value
of the global failed job counter which is at `resque:stat:failed`.
=> allow retrieval of failed job counter

src/main/java/net/greghaines/jesque/worker/WorkerImpl.java, src/main/java/net/greghaines/jesque/worker/WorkerPoolImpl.java
the number of items to keep in the failed queue can not be downsized. the problem is that we always only remove max. 1 item with the `ltrim`. the fix is to trim the list to exactly the size we want.
we also don't need to check the size of the failed queue before trimming, as we can simply `ltrim` all the time now.
=> proper resizing of failed item queue
